### ISSUE TITLE
Modeling Doesn't Work

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-headless#1]
### Describe the Bug

Trying to model using the API (e.g., creating a shape) fails with errors. Many features still rely on the browser APIs, for example [`BpmnOrderingProvider`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/ordering/BpmnOrderingProvider.js).

### Steps to Reproduce

1. Use `modeling.createShape` to create a shape
2. Error

### Expected Behavior

Basic modeling works without having to mock several features.

### Environment

- Library version: 0.0.1 🤡

**Comment by philippfromme** [comment]
Don't get me wrong. I'm very thankful for this library. We just need to fix a couple of things. 🚧 👷🏻 🏗️

**Comment by nikku** [comment]
Could you be more precise on what does not work, and which error you see? 

[BpmnOrderingProvider](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/ordering/BpmnOrderingProvider.js) does not depend on browser APIs in any way.

**Comment by nikku** [comment]
Verified it works via https://github.com/bpmn-io/bpmn-js-headless/commit/3f55978b261b70dcc1d98c1b04c99892a7ea16fa.

Please open an issue and/or update this issue with concrete steps to reproduce.

**Comment by philippfromme** [comment]
Let me check again.

**Comment by philippfromme** [comment]
I was using `createShape` without specifying `target`. 🤦🏻
